# This file created by conda-build 3.24.0
# meta.yaml template originally from:
# /Users/runner/work/bioconda-recipes/bioconda-recipes/recipes/clustalw, last modified Tue May 16 05:40:15 2023
# ------------------------------------------------

package:
  name: clustalw
  version: '2.1'
source:
  md5: 144df8440a0ae083d5167616c8ceeb41
  patches:
    - patch
  url: http://www.clustal.org/download/current/clustalw-2.1.tar.gz
build:
  number: '9'
  string: h85dcccf_9
requirements:
  build:
    - ca-certificates 2023.5.7 h8857fd0_0
    - cctools_osx-64 973.0.1 h48a5a9d_13
    - clang 15.0.7 h694c41f_1
    - clang-15 15.0.7 default_h20dc2f0_1
    - clang_osx-64 15.0.7 h03d6864_2
    - clangxx 15.0.7 default_h20dc2f0_1
    - clangxx_osx-64 15.0.7 h2133e9c_2
    - compiler-rt 15.0.7 h613da45_0
    - compiler-rt_osx-64 15.0.7 h613da45_0
    - icu 72.1 h7336db1_0
    - ld64_osx-64 609 h8ce0179_13
    - libclang-cpp15 15.0.7 default_h20dc2f0_1
    - libcxx 16.0.3 hd57cbcb_0
    - libiconv 1.17 hac89ed1_0
    - libllvm15 15.0.7 h7001e86_1
    - libxml2 2.10.4 h554bb67_0
    - libzlib 1.2.13 hfd90126_4
    - llvm-tools 15.0.7 h7001e86_1
    - make 4.3 h22f3db7_1
    - openssl 3.1.0 h8a1eda9_3
    - sigtool 0.1.3 h88f4db0_0
    - tapi 1100.0.11 h9ce4665_0
    - xz 5.2.6 h775f41a_0
    - zstd 1.5.2 hbc0c0cd_6
  host:
    - libcxx 16.0.3 hd57cbcb_0
  run:
    - libcxx >=15.0.7
test:
  commands:
    - clustalw2 H 2>&1 | grep "CLUSTAL 2.1"
    - clustalw H 2>&1 | grep "CLUSTAL 2.1"
about:
  home: http://www.clustal.org/clustal2/
  license: GNU Lesser GPL
  summary: ClustalW2 is a general purpose multiple sequence alignment program for
    DNA or proteins.
extra:
  copy_test_source_files: true
  final: true
  identifiers:
    - biotools:trinity
    - doi:10.1038/nbt.1883
    - usegalaxy-eu:clustalw
  skip-lints:
    - should_not_be_noarch_source
